version: 2.1
defaults: &defaults
  docker:
    - image: cimg/base:2022.09
      auth:
        username: mydockerhub-user
        password: $DOCKERHUB_PASSWORD
    - image: cimg/mysql:8.0
      auth:
        username: mydockerhub-user
        password: $DOCKERHUB_PASSWORD
      entrypoint:
        [
          "docker-entrypoint.sh",
          "--default-authentication-plugin=mysql_native_password",
        ]
      environment:
        MYSQL_ROOT_PASSWORD: rootpw
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: test_varbase
        MYSQL_USER: user
        MYSQL_PASSWORD: passw0rd
  resource_class: large
commands:
  varbase-build:
    steps:
      - checkout
      - run:
          name: Usefull must have utils
          command: |
            sudo apt -qq update
            sudo apt -qqy install docker-buildx-plugin
            sudo apt -qqy upgrade
            sudo apt -yqq install vim links lynx git diffutils htop curl wget p7zip-full unzip zip sed gcc g++ make
            sudo apt -yqq install libfreetype6-dev libaio1 libaio-dev libonig-dev libpng-dev mysql-client default-mysql-client
            sudo apt -yqq install imagemagick
      - run:
          name: Setup Apache2 and PHP8.4
          command: |
            sudo add-apt-repository ppa:ondrej/php -y
            sudo apt update
            sudo apt upgrade
            sudo apt -yqq install apache2 php8.4 libapache2-mod-php8.4 php8.4-mbstring php8.4-mysql php8.4-xml php8.4-cgi php8.4-cli php8.4-common php8.4-curl php8.4-gd php8.4-imap php8.4-intl php8.4-pspell php8.4-sqlite3 php8.4-tidy php8.4-opcache php8.4-yaml php8.4-bz2 php8.4-readline php8.4-xmlrpc php8.4-enchant php8.4-xsl php8.4-zip php8.4-bcmath php-pear
            sudo a2enmod php8.4
            sudo a2enmod headers rewrite env mime expires ssl
            sudo update-alternatives --set php /usr/bin/php8.4
            echo -e "memory_limit = -1" | sudo tee /etc/php/8.4/apache2/php.ini > /dev/null
            echo -e "max_execution_time = 1200" | sudo tee /etc/php/8.4/apache2/php.ini > /dev/null
            echo -e "error_reporting = E_ALL" | sudo tee /etc/php/8.4/apache2/php.ini > /dev/null
            echo -e "max_input_time = 180" | sudo tee /etc/php/8.4/apache2/php.ini > /dev/null
            echo -e "max_input_vars = 10000" | sudo tee /etc/php/8.4/apache2/php.ini > /dev/null
            echo -e "post_max_size = 64M" | sudo tee /etc/php/8.4/apache2/php.ini > /dev/null
            echo -e "upload_max_filesize = 32M" | sudo tee /etc/php/8.4/apache2/php.ini > /dev/null
            echo -e "max_file_uploads = 40" | sudo tee /etc/php/8.4/apache2/php.ini > /dev/null
            sudo service apache2 restart
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install node js and enable corepack for Yarn 4
          command: |
            curl -sL https://deb.nodesource.com/setup_20.x | sudo bash -
            sudo apt install -y nodejs
            sudo corepack enable
      - run:
          name: Install composer ~2
          command: |
            sudo curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin/ --filename=composer --2;
            composer config -g github-oauth.github.com $GITHUB_TOKEN
      - run:
          name: List tools versions
          command: |
            php --version
            node --version
            yarn --version
            mysql --version
            composer --version
            php -m
            php -i | grep "Loaded Configuration File"
            php --ini
      - run:
          name: Build Varbase with the composer
          command: |
            if [ -d "/var/www/html/test" ]; then
              sudo rm -rf /var/www/html/test -vvv
            fi
            cd /var/www/
            sudo chmod 775 -R .
            sudo chown www-data:circleci -R .
            mkdir /var/www/html/test
            cd /var/www/html/test/
            sudo chmod 775 .
            sudo chown www-data:circleci .
            git clone --branch '11.0.x' https://github.com/vardot/varbase-project.git /var/www/html/test/varbase
            cd /var/www/html/test/varbase
            sudo chmod 775 -R .
            sudo chown www-data:circleci -R .
            composer install --no-interaction -vvv
            sudo chmod 775 -R .
            sudo chown www-data:circleci -R .
      - run:
          name: Point varbase.test at /var/www/html/test/varbase/web
          command: |
            sudo a2enmod headers rewrite env mime expires ssl
            sudo cp /home/circleci/project/.circleci/env/varbase.test.conf /etc/apache2/sites-available/varbase.test.conf
            sudo a2ensite varbase.test
            echo 127.0.0.1 varbase.test | sudo tee -a /etc/hosts
            sudo service apache2 restart
      - run:
          name: Install Varbase with drush
          command: |
            mysql -h 127.0.0.1 -uroot -prootpw --execute="DROP DATABASE IF EXISTS test_varbase;" -vvv
            mysql -h 127.0.0.1 -uroot -prootpw --execute="CREATE DATABASE test_varbase;" -vvv
            cd /var/www/html/test/varbase/web
            ../bin/drush site-install varbase --yes --account-name="webmaster" --account-pass="dD.123123ddd" --account-mail="webmaster@vardot.com" --db-url="mysql://root:rootpw@127.0.0.1/test_varbase" --locale="en" -vvv
            ../bin/drush recipe ../recipes/varbase_dev_base
            ../bin/drush recipe ../recipes/varbase_i18n_base
            ../bin/drush recipe ../recipes/varbase_api_base
            ../bin/drush recipe ../recipes/varbase_auth_base
            ../bin/drush cache:rebuild
      - run:
          name: Add testing users.
          command: |
            cd /var/www/html/test/varbase/recipes/varbase_starter/scripts
            bash add-testing-users.sh
      - run:
          name: Prepare site for testing
          shell: /bin/bash
          command: |
            cd /var/www/html/test/varbase/web
            ../bin/drush pm:uninstall antibot --yes
            ../bin/drush config:set system.performance css.preprocess 0 --yes
            ../bin/drush config:set system.performance js.preprocess 0 --yes
            ../bin/drush config:set system.logging error_level all --yes
            ../bin/drush cache:rebuild
      - run:
          name: Install Playwright browsers
          command: |
            cd /home/circleci/project
            yarn install
            npx playwright install --with-deps chromium

jobs:
  varbase-testing:
    <<: *defaults
    steps:
      - varbase-build
      - run:
          name: Automated Functional Acceptance Testing
          no_output_timeout: 30m
          command: |
            LAUNCH_URL=http://varbase.test yarn test:chromium

workflows:
  version: 2
  varbase-workflow:
    jobs:
      - varbase-testing:
          filters:
            tags:
              only: /^11.0.*/
            branches:
              only: /^11.0.x/
