#!/bin/bash

## Description: Delete testing users
## Usage: delete-testing-users
## Example: ddev delete-testing-users
## Aliases: varbase:delete-testing-users

current_path=$(pwd);

# Include the Bash YAML library.
source ${current_path}/.ddev/commands/web/libs/bash-yaml.sh || exit 1 ;

# Load the list of default users for Varbase.
eval $(parse_yaml ${current_path}/.ddev/commands/web/assets/varbase.users.yml);

for user in ${users[@]}
do
  user_name="user_${user}_name";
  user_mail="user_${user}_mail";
  user_password="user_${user}_password";
  user_role="user_${user}_role";

  echo " ---------------------------------------------------------------- ";
  echo "      User name: ${!user_name}";
  echo "      User mail: ${!user_mail}";
  echo "  User password: ${!user_password}";
  echo "      User role: ${!user_role}";
  echo " ================================================================= ";

  drush user:cancel --delete-content "${!user_name}" --yes;

done
